Don't auto-upgrade amazonwebservices.aws-toolkit-vscode
It causes the `node upgrade-extensions` script to fail with:

> Error: Open VSX already has a more recent version of amazonwebservices.aws-toolkit-vscode: 1.27.0 > 1.27.0-6c4644db65c7